"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const weatherReportControllers_1 = require("../controllers/weatherReportControllers");
const weatherReportController = require('../controllers/weatherReportController');
const router = express_1.Router();
router.get('/', (req, res, next) => res.status(200));
router.post('/weather-report', weatherReportControllers_1.getWeatherReport, weatherReportControllers_1.saveWeatherReport, (req, res, next) => res.status(200));
router.get('/weather-logs', weatherReportControllers_1.getAllWeatherReports, (req, res, next) => res.status(200));
router.delete('/delete-all', weatherReportControllers_1.deleteAllWeatherReports, (req, res, next) => res.status(200));
exports.default = router;
